name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.2
          - snapshot
    steps:
      # GCC & SQLite3 needed for sqlite3 package
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1

      # See https://github.com/ccorsi/setup-sqlite for sqlite version
      # info
      - name: Set up SQLite3
        uses: ccorsi/setup-sqlite@v1.0.1
        with:
          sqlite-version: 3.40.0
          sqlite-year: 2022

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Load the config
        run: |
          ./test-config-batch.sh
